language: objective-c
osx_image: xcode8

git:
  submodules: false

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - WORKSPACE=Restofire.xcworkspace
    - IOS_FRAMEWORK_SCHEME="Restofire-iOS"
    - OSX_FRAMEWORK_SCHEME="Restofire-macOS"
    - TVOS_FRAMEWORK_SCHEME="Restofire-tvOS"
    - WATCHOS_FRAMEWORK_SCHEME="Restofire-watchOS"
    - IOS_SDK=iphonesimulator10.0
    - OSX_SDK=macosx10.12
    - TVOS_SDK=appletvsimulator10.0
    - WATCHOS_SDK=watchsimulator3.0
    - EXAMPLE_SCHEME="Example"
  matrix:
    - DESTINATION="OS=10.0,name=iPhone 7 Plus"     SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"  BUILD_EXAMPLE="YES" RELEASE_READY="YES" POD_LINT="YES"
    - DESTINATION="OS=9.0,name=iPhone 5"           SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="NO"   BUILD_EXAMPLE="YES" RELEASE_READY="NO"  POD_LINT="NO"
    - DESTINATION="arch=x86_64"                    SCHEME="$OSX_FRAMEWORK_SCHEME"     SDK="$OSX_SDK"     RUN_TESTS="YES"  BUILD_EXAMPLE="NO"  RELEASE_READY="NO"  POD_LINT="NO"
    - DESTINATION="OS=10.0,name=Apple TV 1080p"    SCHEME="$TVOS_FRAMEWORK_SCHEME"    SDK="$TVOS_SDK"    RUN_TESTS="YES"  BUILD_EXAMPLE="NO"  RELEASE_READY="NO"  POD_LINT="NO"
    - DESTINATION="OS=9.0,name=Apple TV 1080p"     SCHEME="$TVOS_FRAMEWORK_SCHEME"    SDK="$TVOS_SDK"    RUN_TESTS="YES"  BUILD_EXAMPLE="NO"  RELEASE_READY="NO"  POD_LINT="NO"
    - DESTINATION="OS=3.0,name=Apple Watch - 42mm" SCHEME="$WATCHOS_FRAMEWORK_SCHEME" SDK="$WATCHOS_SDK" RUN_TESTS="NO"   BUILD_EXAMPLE="NO"  RELEASE_READY="NO"  POD_LINT="NO"
    - DESTINATION="OS=2.0,name=Apple Watch - 42mm" SCHEME="$WATCHOS_FRAMEWORK_SCHEME" SDK="$WATCHOS_SDK" RUN_TESTS="NO"   BUILD_EXAMPLE="NO"  RELEASE_READY="NO"  POD_LINT="NO"

before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - brew update
  - brew outdated carthage || brew upgrade carthage

before_script:
  - sh scripts/bootstrap

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty -c;
    else
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi

  # Build Framework in Release and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty -c;
    else
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi

  # Build Example in Debug if specified
  - if [ $BUILD_EXAMPLE == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
     pod lib lint;
   fi

before_deploy:
  - carthage build --no-skip-current
  - carthage archive Restofire
  - carthage archive Alamofire

deploy:
  - provider: releases
    api_key:
      secure: KrjeFZFxA8KFpVpZuPpHzjhJREYmOprCR072mGzEJtuf/J9Auiqqml9EEbx0jtabpajkfbDRdWVjkSG+czc13QhBT4uBRCnPiX3c2t1m1PnaZEkiPTyY17ZFIC0+cyxwpQ1KPludHEy5cJ1JS98C6vzprxhSO1p4IDOBMbZ/AmeD8i+iHIGagvdyZdI0ksPuofm9qlg7aQgAvmz+XivlIEtnp9WuDFH0X62Pg2W2M5fJ2IuMTQXAou5Me+/T2TdorGWnASN+7oemYxBHeF1SCkxxvgZ1zh6RDKWaOhBd7+Sim6Aa6KiDpwkIFHtDFw6GVbmpJOp71Ic6PjEOncbXlTvOc+urLcGwUdeGaGOTuyNjKfmrJcvUHUH3E0cvwFvGqXG1C0A8RUIYjRM+RkenxCcEOZPVhYBeZUdS6uHk1ncnQ6r6QTKP0pmbO0uGlhQ4hWUF03u0psAQfQRAYgNsiZPpP/V8Myc0nLrsHK46E+L/CVbuqg82KtcQT2CfYCV4nmG2a3ii/FXaOLJIe0CZqV0uadfXNTYazjdcXXf48OpimNv0hCoaI+od2lMu88Mb08Ff430dNx3k7T5NlWyPLezkT7OfO2dC4MaXkSdS869+G3JKg6mutBLKTAkVuEUMlDqcGSSKFream+D2AVsNKYPWW68XqzzSF6FXrNA8SqA=
    file:
      - Restofire.framework.zip
      - Alamofire.framework.zip
    skip_cleanup: true
    overwrite: true
    on:
      repo: Restofire/Restofire
      tags: true
      condition: $RELEASE_READY = YES
  - provider: script
    script: sh scripts/cocoapods
    on:
      repo: Restofire/Restofire
      tags: true
      condition: $RELEASE_READY = YES

notifications:
  email: false
  slack:
    rooms:
      secure: biPuXXsOtHEm31pNUlWDYcirs84KKPXv2OJrHFtESjJuxLiIX4Y0flyzhDgFNCtt76yTzKDn2ChA8QPmKX7AWR8VMcjE19YWxzxuFP8X1V6j2QaLZpebneRM/pGvCCXhSJHw1WHh+BQZ5A/G3C0vjxwnGUDg6gxWTFdHSZp2Mmi6P0pzWT4JYNLSZFeFbQ9thLQi6SZMAHiNbumadi+F8QXy4qxCJ2Wem6K9PZvEt3p+UVD3hOodvmvLk/0WHu6pXhoyDEt/B4EJAPiB1lln/x+aVlCv1bhvRVAPLF3hDRPy42ROpVGEn5f4e3Y1ggikw/tbtrpExA9F1dtaVKIJTyUdhq8T/G0k4rps+8bY1nhtXzLRgZXU0UYe9MTg7H20rpOl4Za8AcUCuUKmWxOPYHU4D3qSmFyOE0u7CbriMyRZUVuvbilaAvxPgNjQO7nr6aeYYb3W+tYhHlBRI6klA/MuyHimtlfhnBs7Mm6nA3fZoMSIC9cdVNTmfistBvbSvtPDnWdOuGri9ugqWth1HUo4kS/ItBpZ6GWnKEuJ36tCKy7XLrIqRk9tgPKMxAuMbq5uPNMYUonIHjX/JQYe6VBKLC2N13NDviV/B36HvqYWM5g0qbXk9SgatRaGcRtFHPb4y+RNnBICW7W81YHHSPtLEp36BhX2D2EuQMf/lr8=
